version: '3.7'
services:
  vue:
    build: .
    ports:
      - 3000:8080
    volumes:
      - .:/app
    # command: npm run serve
    command: tail -f /dev/null
    # command: /bin/sh -c "yarn install; yarn serve"